// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateTodoTask(ctx context.Context, arg CreateTodoTaskParams) (TodoList, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodoTask(ctx context.Context, id int64) error
	GetTodoTask(ctx context.Context, id int64) (TodoList, error)
	GetTodoTaskList(ctx context.Context, arg GetTodoTaskListParams) ([]TodoList, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateTodoTask(ctx context.Context, arg UpdateTodoTaskParams) (TodoList, error)
}

var _ Querier = (*Queries)(nil)
